### PR TITLE
error correction in search

### PR DESCRIPTION
**Pull request by thilan7**

### CODE REVIEW

**Comment by KajanM** [comment]
This pull request **introduces 2 alerts** when merging 97195789e1615b2511553d8bbb7e8c0787089655 into 0b5721965fb749104ceb111a057c4384fa33d629 - [view on LGTM.com](https://lgtm.com/projects/g/KajanM/DSVL/rev/pr-a1b5d93d2824b5ed0ee4d04f15b1c6e1dda60f5a)

**new alerts:**

* 1 for Equals on incomparable types
* 1 for Spurious Javadoc @param tags

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by SuKSW** [comment]
Thilan, check this link. In messageObject what you have added as sender ip is a string. The address in a neighbour is of type InetAddress. 

other error it shows is just related to a method documentation

https://lgtm.com/projects/g/KajanM/DSVL/rev/pr-a1b5d93d2824b5ed0ee4d04f15b1c6e1dda60f5a

**Comment by KajanM** [comment]
@thilan7 can you address the change suggested by @SuKSW , front-end and back-end code are about to be merged...

**Comment by thilan7** [comment]
sorry for the late bn.

**Pull request merged**
